project:
  type: website

website:
  title: "GlobalR_WEL"
  favicon: img/granja.png
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Información
      - href: Presentaciones/index.qmd
        text: Presentaciones
    
format:
  html:
    theme:
      #- darkly
      - darkish.scss
    css: styles.css
    toc: true



